### ISSUE TITLE
docs(pt) i18n: Translate `reference/default-theme-layout.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [viniciusdeliz/vitepress#6]

**Comment by savionascimentodev** [comment]
@viniciusdeliz could you assign me?

**Comment by viniciusdeliz** [comment]
Thank you for taking this one, @savionascimentodev!

**Comment by viniciusdeliz** [comment]
Let me know how is your progress on this one @savionascimentodev and if I can lend you a hand with it. Thanks!

**Comment by savionascimentodev** [comment]
Hi @viniciusdeliz, I'm going to finish this task today, it went unnoticed that I shouldn't modify the original file in English, I'm sorry, I noticed that you are using "_slot_" with the underscores, would this be the default for words that will not be translated? (in some cases), I'll join too.

In fact, if you could explain to me where the Brazilian documentation folder is, I think I'm a little lost.

Edit1: You can disregard my friend, I was doing it from main, I wasn't seeing the i18n branch, I'm sorry 😁

**Comment by savionascimentodev** [comment]
@viniciusdeliz, I sent the pull request, if there is anything else that can help let me know!
