### ISSUE TITLE
docs(pt) i18n: Translate `reference/default-theme-badge.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [viniciusdeliz/vitepress#7]

**Comment by savionascimentodev** [comment]
@viniciusdeliz could you assign me?

**Comment by viniciusdeliz** [comment]
Just assigned this one to you as well, @savionascimentodev! Thank you

**Comment by savionascimentodev** [comment]
@viniciusdeliz, my friend will we translate the word 'badge' to 'emblem' or will we leave 'badge' anyway?

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz, my friend will we translate the word 'badge' to 'emblem' or will we leave 'badge' anyway?

@savionascimentodev I used 'distintivo' in another instance. I recall seeing 'placa' for it as well somewhere. But I'm not a fan of both. Let's use 'emblema' as you suggested!

**Comment by savionascimentodev** [comment]
@viniciusdeliz, Should we translate the word ‘Custom Children’ too? If so, what would be the best 'Filho Personalizado'?

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz, Should we translate the word ‘Custom Children’ too? If so, what would be the best 'Filho Personalizado'?

@savionascimentodev that's a tricky one, I'm reading here and it's a bit confusing and hard to translate. I'd write it as 'Filiação Personalizada'. Just a reminder that we should probably not translate elements, their attributes, CSS classes or related, such as `<Badge />`, `--vp-badge`, and else.

**Comment by savionascimentodev** [comment]
I'm sending the file and anything you let me know in pr

@viniciusdeliz One question, will you give permission to this repo, or should I create a fork too?

**Comment by viniciusdeliz** [comment]
> I'm sending the file and anything you let me know in pr
> 
> @viniciusdeliz One question, will you give permission to this repo, or should I create a fork too?

@savionascimentodev as you prefer. I added you as collaborator in this repo. Let me know if you need assistance
