### ISSUE TITLE
docs(pt) i18n: Translate `reference/default-theme-team-page.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [viniciusdeliz/vitepress#8]

**Comment by savionascimentodev** [comment]
@viniciusdeliz could you assign me? 😁

**Comment by viniciusdeliz** [comment]
Assigned as well, thank you @savionascimentodev. Please make sure you're creating branches from the translation branch: https://github.com/viniciusdeliz/vitepress/tree/vitepress-i18n-pt

**Comment by savionascimentodev** [comment]
Ok understood.
