### ISSUE TITLE
docs(pt) i18n: Translate `reference/default-theme-prev-next-links.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [viniciusdeliz/vitepress#9]

**Comment by savionascimentodev** [comment]
@viniciusdeliz could you assign me? 😁

**Comment by viniciusdeliz** [comment]
Resolved by https://github.com/viniciusdeliz/vitepress/commit/d96dae35b0e6e3bfe0d512380c4a4b9da8db17d5
